### ISSUE TITLE
restructure HTML and incorporate CSS 

### ISSUE THREAD

**Issue by zz-hh-aa** [fac30/agency-website--Ollie-Emma#11]
- [x] `<main>` tags: rather than enclose just the top pane / welcome info, it seems like it should hold all the major content of the page: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main
- [x] add CSS classes to relevant HTML

**Comment by electricblues** [comment]
I like the idea, but I wonder if we can't just do this as part of an actual feature maybe? Suppose one would tackle the 'about us' section: it would likely include some html changes, some css adjustments and maybe some js -- which feels to me like more modular & making it easier for us to code in parallel.

What are your thoughts?
