### ISSUE TITLE
create responsiveness for different screen sizes

### ISSUE THREAD

**Issue by zz-hh-aa** [fac30/agency-website--Ollie-Emma#19]
- [ ] create mobile design
- [ ] decide on and implement nav menu behaviour
- [ ] implement mobile design using media queries etc.

**Comment by zz-hh-aa** [comment]
- [ ] Resize images (see [guide](https://developer.chrome.com/docs/lighthouse/performance/uses-responsive-images/?utm_source=lighthouse&utm_medium=devtools)) (from the Lighthouse Best Practice audit)
- [ ] Explicit `width` and `height` for image elements

**Comment by electricblues** [comment]
just brainstorming the checkmarks versus what I believe needs to be done:


> decide on and implement nav menu behaviour

I thought the navbar is ok-ish as it is, with the exception of making the menu button disappear on touch as well

> Resize images (see [guide](https://developer.chrome.com/docs/lighthouse/performance/uses-responsive-images/?utm_source=lighthouse&utm_medium=devtools)) (from the Lighthouse Best Practice audit)
>  Explicit width and height for image elements

I'll cut the images a bit, but I don't think it's a good idea to give them fixed sizes if we want to have a good experience on multiple devices.

What do you think?

**Comment by zz-hh-aa** [comment]
- nav bar: I thought it might work better on mobile to have the nav bar cover the whole screen width--but feel free to do as you see fit 
- image sizing: yeah that makes sense! I just copied the recommendations over, hadn't actually considered that
