### ISSUE TITLE
check accessibility again

### ISSUE THREAD

**Issue by electricblues** [fac30/agency-website--Ollie-Emma#35]
- [x]  check tabindexes  
- [x] use  aria labels if needed
- [x] use lighthouse to check the whole website 
- [x] use the screenreader

**Comment by zz-hh-aa** [comment]
- [x] improve contrast on homes descriptions
- [x] improve contrast on mobile nav bar
- [x] improve contrast on hamburger on mobile 
- [ ] fix carousel screenreader functionality -- only reading first slide

**Comment by zz-hh-aa** [comment]
Accessibility 100 on Lighthouse mobile and desktop audits
