### ISSUE TITLE
Create semantic HTML structure

### ISSUE THREAD

**Issue by zz-hh-aa** [fac30/agency-website--Ollie-Emma#4]
With sections for:

- nav menu
- about the agency
- about the members
- contact form
- footer

**Comment by electricblues** [comment]
is this different compared with  [issue 1](https://github.com/fac30/agency-website--Ollie-Emma/issues/1)?

**Comment by zz-hh-aa** [comment]
I made it before I saw your changes--thought they were just empty files at first! Will close the issue.
